### PR TITLE
pre processing smoothing and masking functions done

### PR DESCRIPTION
**Pull request by gcescobar13**

### CODE REVIEW

**Comment by imranyousuf** [comment]
Looks good

**Comment by gcescobar13** [comment]
@imranyousuf can you help me out on this coverage issue?

**Comment by imranyousuf** [comment]
I will merge it after some writing some test.

**Comment by gcescobar13** [comment]
@imranyousuf i think it passed now

**Comment by imranyousuf** [comment]
@giancarloescobar of course, I will start writing tests. Can you give me an example on how to run it. That way I can test it as well as put in your ReadMe.md

**Comment by imranyousuf** [comment]
Yeah but we still need our coverage to go above 90%. I will try to make that happen today.

**Pull request merged**
