### PR TITLE
altered pre_process.py

### PR DESCRIPTION
**Pull request by gcescobar13**
contains 3 functions
1. smooth_mask()
will smooth data and compute a mask and applies it to the smoothed data. returns 2d
2. masked_data()
calculates and applies mask. returns 2d data
3. smooth_data()
returns smoothed data, 4d array

### CODE REVIEW

**Comment by gcescobar13** [comment]
@imranyousuf can you help me merge this?

**Comment by imranyousuf** [comment]
sure

**Comment by imranyousuf** [comment]
You have to first solve the merge conflict. One you can do it is by pulling from master and then merging your files. Let me know if you still need help

**Comment by imranyousuf** [comment]
Merge conflict solved merging them

**Pull request merged**
